[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "waterlagen"
description = "Waterlagen: rasters en features downloaden en bewerken voor toepassing in waterbeheer"
readme = "README.md"
keywords = ["hydrologie", "waterbeheer", "PDOK", "BAG", "BGT", "AHN"]
authors = [
    { name = "Daniel Tollenaar", email = "daniel@d2hydro.nl" },
    { name = "Wouter van Esse", email = "w.vanesse@hhnk.nl" }
]
license = { text = "MIT" }

urls = { "Source" = "https://github.com/d2hydro/waterlagen", "Documentation" = "https://d2hydro.github.io/waterlagen/" }

requires-python = ">=3.11"
dependencies = [
    "gdal",
    "geopandas",
    "pydantic",
    "pydantic-settings",
    "rasterio",
    "pyogrio",
    "pyproj",
    "numpy",
    "requests",
    "shapely",
    "affine",
    "tqdm"
]
dynamic = ["version"]

[project.optional-dependencies]
tests = ["pytest"]

[tool.hatch.version]
source = "vcs"
tag-pattern = '^v?(?P<version>\d{4}\.\d{1,2}\.\d+(?:(?:a|b|rc)\d+)?(?:\.post\d+)?(?:\.dev\d+)?)$'

[tool.hatch.version.raw-options]
version_scheme = "no-guess-dev"

[tool.hatch.build.targets.wheel]
packages = ["src/waterlagen"]

[tool.hatch.build.targets.wheel.force-include]
"src/waterlagen/resources/landsgrens.gpkg" = "waterlagen/resources/landsgrens.gpkg"

[tool.hatch.build.targets.sdist.force-include]
"src/waterlagen/resources/landsgrens.gpkg" = "src/waterlagen/resources/landsgrens.gpkg"

